hwdec=vaapi
# hwdec=auto-safe                
hwdec=auto
# hwdec=vaapi
# hwdec=auto-unsafe

keepaspect=yes

### --- Audio ---
ao=pipewire
audio-channels=auto
volume-max=100

### --- Interface & Behavior ---
# uosc
osc=no
border=no
title-bar=no

cursor-autohide=1000
save-position-on-quit=yes
# uosc provides seeking & volume indicators (via flash-timeline and flash-volume commands)
# uosc will draw its own window controls and border if you disable window border
border=no
### --- Subtitles & Screenshots ---
sub-auto=fuzzy
screenshot-template="%F - [%P] (%#01n)"
slang=sl,en,eng,enUS
alang=en,eng
autofit=50%
autocreate-playlist=same
script-opts=ytdl_hook-ytdlp_path=yt-dlp
ytdl-format=bestvideo+bestaudio/best
### --- Profiles ---

[ytdlp-firefox]
ytdl-raw-options=user-agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0'

[cookies]
cookies=yes
cookies-file=~/.mozilla/firefox/PROFILE.default-release/cookies.sqlite

[voyo]
http-header-fields='User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0'
