app_id kitty-quick-access
# Start the drop-down window at 80% screen width
placement top-center
# Make the background 90% opaque
lines 40

margin_top 4
margin_left 4

background_opacity 0.9
hide_on_focus_loss no
