# ----------------------------------------------------- 
# Monitor Setup
# name: "dell-phillips"
# ----------------------------------------------------- 


monitor=DP-2,2560x1440@165, 0x0,    1,      bitdepth,10,    vrr,1,    
# monitor=DP-3,3840x2160@60,  2560x0, 1.5,    bitdepth,10
monitor=DP-3,disable