# Add your additional Hyprland configurations here
# 
# This is an additional key binding 
# bind = $mainMod CTRL, up, workspace, empty
# 
# Example for xwayland
# xwayland {
#   force_zero_scaling = true
# }

# qt5ct environment variable
# env = QT_QPA_PLATFORMTHEME,qt5ct

# SDL version
env = SDL_VIDEODRIVER,wayland
# env = SDL_VIDEODRIVER,x11

# No Hardware Cursor
# cursor {
#     no_hardware_cursors = false
# }

# Load nwg-dock-hyprland
# Install it first with yay -S nwg-hyprland-dock
# exec-once = ~/.config/nwg-dock-hyprland/launch.sh

# env = XDG_MENU_PREFIX,arch-

plugin {
    split-monitor-workspaces {
        count = 5
        keep_focused = 0
        enable_notifications = 0
        enable_persistent_workspaces = 1
    }
}

$mainMod = SUPER

debug {
    overlay = false
    disable_logs = true
    enable_stdout_logs = true
}



bind = , code:49, togglespecialworkspace, magic

bind = SUPER, C, movetoworkspace, special
# Switch workspaces with mainMod + [0-5]
# bind = $mainMod, 1, split-workspace, 1
# bind = $mainMod, 2, split-workspace, 2
# bind = $mainMod, 3, split-workspace, 3
# bind = $mainMod, 4, split-workspace, 4
# bind = $mainMod, 5, split-workspace, 5

# # Move active window to a workspace with mainMod + SHIFT + [0-5]
# bind = $mainMod SHIFT, 1, split-movetoworkspacesilent, 1
# bind = $mainMod SHIFT, 2, split-movetoworkspacesilent, 2
# bind = $mainMod SHIFT, 3, split-movetoworkspacesilent, 3
# bind = $mainMod SHIFT, 4, split-movetoworkspacesilent, 4
# bind = $mainMod SHIFT, 5, split-movetoworkspacesilent, 5