
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here

general {
    allow_tearing = true
}

input {
    kb_layout = us, si
    follow_mouse = 1

    touchpad {
        natural_scroll = no
    }
    accel_profile = flat
    sensitivity = 0
    force_no_accel = 0
    numlock_by_default = true
}

