scrollback_lines 20000
wheel_scroll_min_lines 1
wheel_scroll_multiplier 1
scrollbar always
scrollbar_interactive yes
scrollbar_jump_on_click yes
scrollbar_handle_color #1a1b26
scrollbar_handle_opacity 1
scrollbar_track_color #000000
# Browse scrollback with less
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
map f10 launch --stdin-source=@screen_scrollback --stdin-add-formatting --type=overlay less +G -R
# kitty-scrollback.nvim kitten alias
action_alias kitty_scrollback_nvim kitten '$HOME/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py'
# Browse scrollback buffer in nvim
map ctrl+shift+h kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map ctrl+shift+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
# Scroll to the nextt shell prompt
map ctrl+shift+x scroll_to_prompt 1
# Scroll to the previous shell prompt
map ctrl+shift+z scroll_to_prompt -1
# Show clicked command output in nvim
# mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output
# Open links with the mouse
mouse_map left click ungrabbed mouse_handle_click selection link prompt
# Paste from clipboard with middle click
; mouse_map middle click ungrabbed paste_from_clipboard
# Select command output with mouse
mouse_map right press ungrabbed mouse_select_command_output