--ozone-platform-hint=auto
# --enable-features=UseOzonePlatform

--ozone-platform=wayland


# --use-gl=angle
#--use-angle=vulkan
--enable-accelerated-video-decode
# --enable-features=VaapiIgnoreDriverChecks,VaapiVideoDecoder,UseMultiPlaneFormatForHardwareVideo
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoEncoder,VaapiVideoDecoder,VaapiIgnoreDriverChecks
